# fly.toml app configuration file generated for stremio on 2024-09-05T00:35:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stremio'
primary_region = 'eze'

[build]
dockerfile = "./Dockerfile-stremio"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-1x'
