# fly.toml app configuration file generated for real-time-indexer on 2024-10-02T19:55:26-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'real-time-indexer'
primary_region = 'eze'

[build]
dockerfile = "./Dockerfile-real-time-indexer"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-1x'
