name: CI

env:
  SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
  SUPABASE_BASE_URL: ${{ secrets.SUPABASE_BASE_URL }}
  OPEN_SUBTITLES_API_KEY: ${{ secrets.OPEN_SUBTITLES_API_KEY }}
  TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
  PUBLIC_API_BASE_URL_DEVELOPMENT: ${{ secrets.PUBLIC_API_BASE_URL_DEVELOPMENT }}
  PUBLIC_API_BASE_URL_PRODUCTION: ${{ secrets.PUBLIC_API_BASE_URL_PRODUCTION }}

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11

      - name: Install dependencies
        run: bun install

      - name: Compile CLI
        run: cd packages/cli && bun run build

      - name: Set execution permissions for the binary
        run: chmod +x packages/cli/bin/subtis

      - name: Run lint
        run: bun run lint

      - name: Run tests
        run: bun run test
